<?php
$closedState  = $closed_state  ?? null;
$closedReason = $closed_reason ?? null;
$storeName = $q->store->store_name ?? 'Business';
$status = $q->lifecycle_status ?? 'issued';
$canRespond = !empty($token) && $status === 'issued' && (empty($q->sales_status) || $q->sales_status !== 'Converted');
$money = function($amount) use ($q) { return htmlspecialchars(($q->store->currency ?? '') . ' ' . number_format((float)$amount,2)); };
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= htmlspecialchars($storeName) ?> — Quotation <?= htmlspecialchars($q->quotation_code ?? '') ?></title>
<style>body{margin:0;background:#f4f6fa;color:#182230;font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.wrap{max-width:760px;margin:32px auto;padding:0 16px}.card{background:#fff;border:1px solid #e2e7ef;border-radius:14px;padding:24px;margin-bottom:16px;box-shadow:0 4px 18px #13243a0a}h1{margin:0 0 4px;font-size:24px}.muted{color:#667085}.total{font-size:24px;font-weight:750}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{text-align:left;padding:10px 8px;border-bottom:1px solid #edf0f4}td:last-child,th:last-child{text-align:right}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}button{border:0;border-radius:8px;padding:11px 17px;font-weight:700;cursor:pointer}.accept{background:#087443;color:#fff}.decline{background:#fff;color:#a32323;border:1px solid #e2baba}textarea{width:100%;box-sizing:border-box;min-height:82px;padding:10px;border:1px solid #cbd2dc;border-radius:8px;font:inherit}label{display:block;font-weight:650;margin:14px 0 6px}.notice{background:#eaf7ef;padding:12px;border-radius:8px}.error{background:#fff0ee;color:#942b1f;padding:12px;border-radius:8px}.small{font-size:13px}</style></head><body><main class="wrap">
<section class="card"><div class="muted"><?= htmlspecialchars($storeName) ?></div><h1>Quotation <?= htmlspecialchars($q->quotation_code ?? '') ?></h1><div class="muted">Prepared for <?= htmlspecialchars($q->customer->customer_name ?? 'Customer') ?> · <?= htmlspecialchars($q->quotation_date ?? '') ?></div>
<?php if(!empty($notice)): ?><p class="notice"><?= htmlspecialchars($notice) ?></p><?php endif; ?><?php if(!empty($error)): ?><p class="error"><?= htmlspecialchars($error) ?></p><?php endif; ?>
<p><span class="muted">Total</span><br><span class="total"><?= $money($q->grand_total) ?></span></p>
<?php if(!empty($q->expire_date)): ?><p class="small muted">Valid until <?= htmlspecialchars($q->expire_date) ?></p><?php endif; ?>
<?php if(!empty($q->quotation_note)): ?><p><?= nl2br(htmlspecialchars($q->quotation_note)) ?></p><?php endif; ?>
</section>
<section class="card"><h2>Items</h2><table><thead><tr><th>Description</th><th>Qty</th><th>Total</th></tr></thead><tbody>
<?php foreach(($q->items ?? []) as $item): ?><tr><td><?= htmlspecialchars($item->item_name ?? 'Item') ?><?php if(!empty($item->description)): ?><br><span class="muted small"><?= htmlspecialchars($item->description) ?></span><?php endif; ?></td><td><?= htmlspecialchars((string)$item->quotation_qty) ?></td><td><?= $money($item->total_cost) ?></td></tr><?php endforeach; ?>
</tbody></table></section>
<?php if($canRespond): ?><section class="card"><h2>Your response</h2><p class="muted">Accept to confirm you want to proceed, or decline and leave a note for the business.</p><form method="post" action="<?= site_url('quote_response/respond/'.rawurlencode($token)) ?>"><input type="hidden" name="<?= $this->security->get_csrf_token_name() ?>" value="<?= htmlspecialchars($this->security->get_csrf_hash()) ?>"><label for="note">Note (required when declining, optional when accepting)</label><textarea id="note" name="note" maxlength="255" placeholder="Questions, requested changes, or your note"></textarea><div class="actions"><button class="accept" name="decision" value="accepted">Accept quotation</button><button class="decline" name="decision" value="declined">Decline quotation</button></div></form></section>
<?php elseif($closedState): ?><section class="card"><strong><?= $closedState === 'expired' ? 'This response link has expired' : 'This response link is no longer active' ?></strong><p class="muted"><?= htmlspecialchars($closedReason ?? '') ?></p><?php if(!empty($q->response_reason)): ?><p class="small muted">Previously recorded note: <?= nl2br(htmlspecialchars($q->response_reason)) ?></p><?php endif; ?></section>
<?php else: ?><section class="card"><strong>Status: <?= htmlspecialchars(ucfirst($status)) ?></strong><?php if($status==='issued' && !empty($q->sales_status) && $q->sales_status==='Converted'): ?><p>This quotation has already been converted to an invoice.</p><?php elseif($status==='issued'): ?><p>This response link has expired. Please contact <?= htmlspecialchars($storeName) ?> for a current quotation.</p><?php endif; ?><?php if(!empty($q->response_reason)): ?><p><?= nl2br(htmlspecialchars($q->response_reason)) ?></p><?php endif; ?></section><?php endif; ?>
</main></body></html>
